language: python
python:
    - "3.4"
    - "2.7"
install:
    - pip install flake8
script:
    - "nosetests"
    - "flake8 sudoku_json2pdf/*.py"
notifications:
    email:
        - mathyassu@gmail.com
